# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/GPTexp',
                'doc_host': 'https://Bullish-Design.github.io',
                'git_url': 'https://github.com/Bullish-Design/GPTexp',
                'lib_path': 'GPTexp'},
  'syms': {'GPTexp.core': {'GPTexp.core.foo': ('core.html#foo', 'GPTexp/core.py')}}}
